<div class="space-y-4">
 <div><label for="name" class="block text-sm font-semibold">Nama</label><input id="name" name="name" required maxlength="255" value="{{ old('name',$tenant->name ?? '') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
 <div><label for="phone" class="block text-sm font-semibold">Telepon</label><input id="phone" name="phone" maxlength="16" value="{{ old('phone',$tenant->phone ?? '') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('phone')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
 <div><label for="email" class="block text-sm font-semibold">Surel</label><input id="email" name="email" type="email" value="{{ old('email',$tenant->email ?? '') }}" class="mt-1 w-full rounded-lg border-slate-300">@error('email')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
 <div><label for="unit_id" class="block text-sm font-semibold">Unit</label><select id="unit_id" name="unit_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Belum ditempatkan</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected(old('unit_id',$tenant->unit_id ?? '') == $unit->id)>{{ $unit->property->name }} — {{ $unit->unit_number }}</option>@endforeach</select>@error('unit_id')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
 <div><label for="status" class="block text-sm font-semibold">Status</label><select id="status" name="status" class="mt-1 w-full rounded-lg border-slate-300"><option value="active" @selected(old('status',$tenant->status->value ?? 'active') === 'active')>Aktif</option><option value="inactive" @selected(old('status',$tenant->status->value ?? '') === 'inactive')>Nonaktif</option></select>@error('status')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
 <fieldset class="border-t border-slate-200 pt-4"><legend class="font-semibold">Data tersimpan terenkripsi</legend><div class="mt-3 grid gap-4 sm:grid-cols-2"><div><label for="identity_number" class="block text-sm">Nomor identitas</label><input id="identity_number" name="identity_number" autocomplete="off" class="mt-1 w-full rounded-lg border-slate-300">@error('identity_number')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="date_of_birth" class="block text-sm">Tanggal lahir</label><input id="date_of_birth" name="date_of_birth" type="date" autocomplete="off" class="mt-1 w-full rounded-lg border-slate-300">@error('date_of_birth')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="gender" class="block text-sm">Jenis kelamin</label><input id="gender" name="gender" autocomplete="off" class="mt-1 w-full rounded-lg border-slate-300">@error('gender')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="occupation" class="block text-sm">Pekerjaan</label><input id="occupation" name="occupation" autocomplete="off" class="mt-1 w-full rounded-lg border-slate-300">@error('occupation')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="emergency_contact_name" class="block text-sm">Nama kontak darurat</label><input id="emergency_contact_name" name="emergency_contact_name" autocomplete="off" class="mt-1 w-full rounded-lg border-slate-300">@error('emergency_contact_name')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label for="emergency_contact_phone" class="block text-sm">Telepon kontak darurat</label><input id="emergency_contact_phone" name="emergency_contact_phone" autocomplete="off" class="mt-1 w-full rounded-lg border-slate-300">@error('emergency_contact_phone')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div></div></fieldset>
 <p class="text-sm text-slate-600">Data identitas dan kontak darurat disimpan terenkripsi dan tidak ditampilkan dalam daftar.</p>
</div>
