<x-app-layout>
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
 <p class="text-sm font-semibold text-rentara-teal">Ruang kerja aktif: {{ $workspace->name }}</p>
 <div class="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 class="rentara-page-title">Daftar tenant</h1><p class="mt-2 text-slate-600">Kelola data tenant dan penempatan unit.</p></div><a href="{{ route('app.tenants.create') }}" class="rounded-lg bg-rentara-blue px-4 py-2.5 text-sm font-semibold text-white">Tambah tenant</a></div>
 @if(session('status'))<p class="mt-4 rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800" role="status">{{ session('status') }}</p>@endif
 <form method="GET" class="mt-6 flex gap-2"><label class="sr-only" for="q">Cari tenant</label><input id="q" name="q" value="{{ $search }}" placeholder="Cari nama, telepon, surel, atau nomor unit" class="rounded-lg border-slate-300"><button class="rounded-lg bg-slate-700 px-4 py-2 text-sm font-semibold text-white">Cari</button></form>
 <section class="rentara-card mt-4 overflow-x-auto">@if($tenants->isEmpty())<div class="px-6 py-12 text-center"><h2 class="font-display text-lg font-bold text-rentara-navy">Belum ada tenant</h2></div>@else
 <table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead><tr class="text-xs font-semibold uppercase tracking-wide text-slate-500"><th class="px-4 py-3">Nama</th><th class="px-4 py-3">Telepon</th><th class="px-4 py-3">Surel</th><th class="px-4 py-3">Unit</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($tenants as $tenant)<tr><td class="px-4 py-3 font-semibold"><a class="text-rentara-blue hover:underline" href="{{ route('app.tenants.show',$tenant) }}">{{ $tenant->name }}</a></td><td class="px-4 py-3">{{ $tenant->phone ?? '—' }}</td><td class="px-4 py-3">{{ $tenant->email ?? '—' }}</td><td class="px-4 py-3">{{ $tenant->unit?->unit_number ?? 'Belum ditempatkan' }}</td><td class="px-4 py-3">{{ $tenant->status->value === 'active' ? 'Aktif' : 'Nonaktif' }}</td></tr>@endforeach</tbody></table><div class="px-4 py-4">{{ $tenants->links() }}</div>@endif</section>
</div></x-app-layout>
