@if($errors->any())<div role="alert" class="rounded-lg bg-red-50 p-4 text-sm text-red-800"><p class="font-semibold">Periksa kembali isian berikut:</p><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-4 sm:grid-cols-2">
    <div><label for="title" class="block text-sm font-semibold text-rentara-navy">Judul</label><input id="title" name="title" required maxlength="160" value="{{ old('title', $t->title ?? '') }}" class="mt-1 block w-full rounded-lg border-slate-300 text-sm" />@error('title')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="priority" class="block text-sm font-semibold text-rentara-navy">Prioritas</label><select id="priority" name="priority" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@foreach(['low'=>'Rendah','normal'=>'Normal','high'=>'Tinggi','urgent'=>'Mendesak'] as $value=>$label)<option value="{{ $value }}" @selected(old('priority', $t->priority?->value ?? 'normal') === $value)>{{ $label }}</option>@endforeach</select>@error('priority')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
</div>
<div><label for="description" class="block text-sm font-semibold text-rentara-navy">Deskripsi</label><textarea id="description" name="description" required maxlength="10000" rows="5" class="mt-1 block w-full rounded-lg border-slate-300 text-sm">{{ old('description', $t->description ?? '') }}</textarea>@error('description')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
<div class="grid gap-4 sm:grid-cols-2">
    <div><label for="property_id" class="block text-sm font-semibold text-rentara-navy">Properti</label><select id="property_id" name="property_id" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih properti</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected((string)old('property_id',$t->property_id ?? '') === (string)$property->id)>{{ $property->name }}</option>@endforeach</select>@error('property_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="unit_id" class="block text-sm font-semibold text-rentara-navy">Unit</label><select id="unit_id" name="unit_id" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih unit</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected((string)old('unit_id',$t->unit_id ?? '') === (string)$unit->id)>{{ $unit->property?->name }} — {{ $unit->unit_number }}</option>@endforeach</select>@error('unit_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
</div>
<div><label for="tenant_id" class="block text-sm font-semibold text-rentara-navy">Tenant <span class="font-normal text-slate-500">(opsional)</span></label><select id="tenant_id" name="tenant_id" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Tanpa tenant</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected((string)old('tenant_id',$t->tenant_id ?? '') === (string)$tenant->id)>{{ $tenant->name }} — unit {{ $tenant->unit?->unit_number }}</option>@endforeach</select>@error('tenant_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
<div class="grid gap-4 sm:grid-cols-3"><div><label for="estimated_cost" class="block text-sm font-semibold text-rentara-navy">Estimasi biaya (Rp)</label><input id="estimated_cost" name="estimated_cost" type="number" min="0" inputmode="numeric" value="{{ old('estimated_cost',$t->estimated_cost ?? '') }}" class="mt-1 block w-full rounded-lg border-slate-300 text-sm" />@error('estimated_cost')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div><div><label for="actual_cost" class="block text-sm font-semibold text-rentara-navy">Biaya aktual (Rp)</label><input id="actual_cost" name="actual_cost" type="number" min="0" inputmode="numeric" value="{{ old('actual_cost',$t->actual_cost ?? '') }}" class="mt-1 block w-full rounded-lg border-slate-300 text-sm" />@error('actual_cost')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div><div><label for="charged_to" class="block text-sm font-semibold text-rentara-navy">Dibebankan kepada</label><select id="charged_to" name="charged_to" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Belum ditentukan</option><option value="owner" @selected(old('charged_to',$t->charged_to?->value ?? '') === 'owner')>Pemilik</option><option value="tenant" @selected(old('charged_to',$t->charged_to?->value ?? '') === 'tenant')>Tenant</option></select>@error('charged_to')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div></div>
