@php
    $statuses = ['submitted'=>'Diajukan','reviewed'=>'Ditinjau','assigned'=>'Ditugaskan','in_progress'=>'Sedang dikerjakan','waiting'=>'Menunggu','resolved'=>'Selesai','closed'=>'Ditutup','rejected'=>'Ditolak'];
    $priorities = ['low'=>'Rendah','normal'=>'Normal','high'=>'Tinggi','urgent'=>'Mendesak'];
    $next = ['submitted'=>['reviewed','rejected'],'reviewed'=>['assigned','rejected'],'assigned'=>['in_progress','rejected'],'in_progress'=>['waiting','resolved','rejected'],'waiting'=>['in_progress','resolved'],'resolved'=>['closed'],'closed'=>[],'rejected'=>[]];
    $money = fn ($value) => $value === null ? '—' : 'Rp '.number_format($value, 0, ',', '.');
@endphp
<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-center justify-between gap-3"><h1 class="font-semibold text-xl text-rentara-navy">{{ $t->title }}</h1><div class="flex gap-2"><a href="{{ route('app.maintenance-tickets.index') }}" class="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">Kembali</a>@can('update',$t)<a href="{{ route('app.maintenance-tickets.edit',$t) }}" class="rounded-lg bg-rentara-navy px-3 py-2 text-sm font-semibold text-white">Ubah</a>@endcan</div></div></x-slot>
    <div class="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
        @if(session('status'))<div role="status" class="rounded-lg bg-green-50 p-4 text-sm text-green-800">{{ session('status') }}</div>@endif
        @if($errors->any())<div role="alert" class="rounded-lg bg-red-50 p-4 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="grid gap-5 lg:grid-cols-3">
            <article class="space-y-5 rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><div class="flex flex-wrap gap-2"><span class="rounded-full bg-slate-100 px-3 py-1 text-sm">{{ $statuses[$t->status->value] ?? $t->status->value }}</span><span class="rounded-full bg-amber-50 px-3 py-1 text-sm text-amber-900">Prioritas: {{ $priorities[$t->priority->value] ?? $t->priority->value }}</span></div><div><h2 class="text-sm font-semibold text-slate-500">Deskripsi</h2><p class="mt-2 whitespace-pre-line text-slate-800">{{ $t->description }}</p></div><dl class="grid gap-4 border-t border-slate-100 pt-4 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Properti</dt><dd class="font-medium">{{ $t->property?->name ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">Unit</dt><dd class="font-medium">{{ $t->unit?->unit_number ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">Tenant</dt><dd class="font-medium">{{ $t->tenant?->name ?? 'Tidak ada' }}</dd></div><div><dt class="text-sm text-slate-500">Dibuat oleh</dt><dd class="font-medium">{{ $t->submitter?->name ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">Estimasi biaya</dt><dd class="font-medium">{{ $money($t->estimated_cost) }}</dd></div><div><dt class="text-sm text-slate-500">Biaya aktual</dt><dd class="font-medium">{{ $money($t->actual_cost) }}{{ $t->charged_to ? ' — '.($t->charged_to->value === 'tenant' ? 'Tenant' : 'Pemilik') : '' }}</dd></div></dl></article>
            <aside class="space-y-5">
                @can('transition',$t)<section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold text-rentara-navy">Tindakan siklus</h2><form method="POST" action="{{ route('app.maintenance-tickets.transition',$t) }}" class="mt-4 space-y-3">@csrf<label for="status" class="block text-sm font-semibold">Status berikutnya</label><select id="status" name="status" required class="block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih status</option>@foreach($next[$t->status->value] ?? [] as $value)<option value="{{ $value }}">{{ $statuses[$value] }}</option>@endforeach</select><label for="reason" class="block text-sm font-semibold">Alasan <span class="font-normal text-slate-500">(wajib untuk menunggu/ditolak)</span></label><textarea id="reason" name="reason" rows="2" maxlength="2000" class="block w-full rounded-lg border-slate-300 text-sm"></textarea><button class="w-full rounded-lg bg-rentara-navy px-3 py-2 text-sm font-semibold text-white">Perbarui status</button></form><form method="POST" action="{{ route('app.maintenance-tickets.assign',$t) }}" class="mt-5 space-y-3 border-t border-slate-100 pt-5">@csrf<label for="assigned_to" class="block text-sm font-semibold">Petugas</label><select id="assigned_to" name="assigned_to" required class="block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih petugas</option>@foreach($assignmentCandidates as $candidate)<option value="{{ $candidate->id }}" @selected($t->assigned_to === $candidate->id)>{{ $candidate->name }}</option>@endforeach</select><button class="w-full rounded-lg border border-rentara-navy px-3 py-2 text-sm font-semibold text-rentara-navy">Tugaskan</button></form></section>@endcan
                <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold text-rentara-navy">Petugas saat ini</h2><p class="mt-2 text-sm">{{ $t->assignee?->name ?? 'Belum ditugaskan' }}</p></section>
            </aside>
        </div>
        <section class="rounded-xl bg-white p-5 shadow-sm" aria-labelledby="history-heading"><h2 id="history-heading" class="font-semibold text-rentara-navy">Riwayat status</h2>@if($t->history->count())<ol class="mt-4 space-y-4 border-l-2 border-slate-200 pl-5">@foreach($t->history as $entry)<li><p class="font-medium">{{ $entry->from_status ? ($statuses[$entry->from_status->value] ?? $entry->from_status->value).' → ' : '' }}{{ $statuses[$entry->to_status->value] ?? $entry->to_status->value }}</p><p class="text-sm text-slate-500">{{ $entry->actor?->name ?? 'Pengguna' }}@if($entry->reason) — {{ $entry->reason }}@endif</p></li>@endforeach</ol>@else<p class="mt-3 text-sm text-slate-600">Belum ada riwayat.</p>@endif</section>
        <section class="rounded-xl bg-white p-5 shadow-sm" aria-labelledby="photos-heading"><h2 id="photos-heading" class="font-semibold text-rentara-navy">Foto tiket</h2>
            @can('view',$t)<form method="POST" action="{{ route('app.maintenance-tickets.media.store',$t) }}" enctype="multipart/form-data" class="mt-4 flex flex-wrap items-end gap-3">@csrf<div><label for="file" class="block text-sm font-semibold">Tambah foto</label><input id="file" name="file" type="file" accept="image/jpeg,image/png,image/webp" required class="mt-1 block max-w-full text-sm" /><p class="mt-1 text-xs text-slate-500">JPG, PNG, atau WebP; maksimal 10 MB.</p></div><button class="rounded-lg bg-rentara-navy px-3 py-2 text-sm font-semibold text-white">Unggah</button></form>@endcan
            @if($t->media->count())<div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach($t->media as $media)<figure><a href="{{ route('app.media.stream',$media) }}"><img src="{{ route('app.media.stream',$media) }}" alt="Foto tiket {{ $t->title }}" class="aspect-square w-full rounded-lg object-cover" /></a>@can('delete',$media)<form method="POST" action="{{ route('app.media.destroy',$media) }}" class="mt-2">@csrf @method('DELETE')<button class="text-sm font-semibold text-red-700 underline">Hapus foto</button></form>@endcan</figure>@endforeach</div>@else<p class="mt-4 text-sm text-slate-600">Belum ada foto.</p>@endif
        </section>
    </div>
</x-app-layout>
