@php($properties = $properties ?? $workspace->properties()->with('units')->get())
<div class="grid gap-4 sm:grid-cols-2">
    <div><label for="contract_number" class="block text-sm font-semibold text-rentara-navy">Nomor kontrak</label><input id="contract_number" name="contract_number" value="{{ old('contract_number', $contract?->contract_number) }}" required maxlength="100" class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('contract_number')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div>
    <div><label for="property_id" class="block text-sm font-semibold text-rentara-navy">Properti</label><select id="property_id" name="property_id" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih properti</option>@foreach($properties as $property)<option value="{{ $property->id }}" @selected((string)old('property_id', $contract?->property_id) === (string)$property->id)>{{ $property->name }}</option>@endforeach</select>@error('property_id')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div>
</div>
<div><label for="unit_id" class="block text-sm font-semibold text-rentara-navy">Unit</label><select id="unit_id" name="unit_id" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih unit</option>@foreach($properties as $property)@foreach($property->units as $unit)<option value="{{ $unit->id }}" data-property="{{ $property->id }}" @selected((string)old('unit_id', $contract?->unit_id) === (string)$unit->id)>{{ $property->name }} · {{ $unit->unit_number }}</option>@endforeach @endforeach</select>@error('unit_id')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div>
<div class="grid gap-4 sm:grid-cols-2"><div><label for="start_date" class="block text-sm font-semibold text-rentara-navy">Tanggal mulai</label><input id="start_date" name="start_date" type="date" value="{{ old('start_date', $contract?->start_date?->format('Y-m-d')) }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('start_date')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div><div><label for="end_date" class="block text-sm font-semibold text-rentara-navy">Tanggal berakhir</label><input id="end_date" name="end_date" type="date" value="{{ old('end_date', $contract?->end_date?->format('Y-m-d')) }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('end_date')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div></div>
<div class="grid gap-4 sm:grid-cols-2"><div><label for="rental_price" class="block text-sm font-semibold text-rentara-navy">Harga sewa (Rp)</label><input id="rental_price" name="rental_price" type="number" min="0" inputmode="numeric" value="{{ old('rental_price', $contract?->rental_price) }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('rental_price')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div><div><label for="deposit_amount" class="block text-sm font-semibold text-rentara-navy">Deposit (Rp)</label><input id="deposit_amount" name="deposit_amount" type="number" min="0" inputmode="numeric" value="{{ old('deposit_amount', $contract?->deposit_amount) }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('deposit_amount')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div></div>
<div><label for="notes" class="block text-sm font-semibold text-rentara-navy">Catatan <span class="font-normal text-slate-500">(opsional)</span></label><textarea id="notes" name="notes" rows="3" maxlength="2000" class="mt-1 block w-full rounded-lg border-slate-300 text-sm">{{ old('notes', $contract?->notes) }}</textarea>@error('notes')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div>
