<x-app-layout>
    @php
        $labels = ['draft'=>'Draft','pending'=>'Menunggu aktivasi','active'=>'Aktif','expiring'=>'Akan berakhir','completed'=>'Selesai','terminated'=>'Dihentikan','cancelled'=>'Dibatalkan'];
        $status = $contract->status->value;
        $canEdit = in_array($status, ['draft', 'pending', 'cancelled'], true);
    @endphp
    <div class="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
        <a href="{{ route('app.contracts.index') }}" class="text-sm font-semibold text-slate-600 hover:underline">← Kembali ke kontrak</a>
        <div class="mt-3 flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold text-rentara-teal">{{ $contract->property?->name }} · {{ $contract->unit?->unit_number }}</p><h1 class="rentara-page-title">{{ $contract->contract_number }}</h1></div><span class="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-700">{{ $labels[$status] ?? $status }}</span></div>
        @if(session('status'))<p class="mt-4 rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800" role="status">{{ session('status') }}</p>@endif
        @if($errors->any())<div class="mt-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert" aria-labelledby="contract-errors"><p id="contract-errors" class="font-semibold">Periksa kembali data yang dikirim.</p><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        <section class="rentara-card mt-6 p-6"><h2 class="font-display text-lg font-bold text-rentara-navy">Ringkasan kontrak</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Periode</dt><dd class="font-semibold">{{ $contract->start_date->format('d/m/Y') }} – {{ $contract->end_date->format('d/m/Y') }}</dd></div><div><dt class="text-sm text-slate-500">Harga sewa</dt><dd class="font-semibold">Rp{{ number_format($contract->rental_price, 0, ',', '.') }}</dd></div><div><dt class="text-sm text-slate-500">Deposit</dt><dd class="font-semibold">Rp{{ number_format($contract->deposit_amount, 0, ',', '.') }}</dd></div><div><dt class="text-sm text-slate-500">Catatan</dt><dd>{{ $contract->notes ?: '—' }}</dd></div>@if($contract->status === \App\Enums\ContractStatus::Terminated)<div><dt class="text-sm text-slate-500">Alasan penghentian</dt><dd class="whitespace-pre-wrap">{{ $contract->termination_reason ?: '—' }}</dd></div>@endif</dl>
            @if($canEdit)<details class="mt-6 border-t border-slate-200 pt-4"><summary class="cursor-pointer font-semibold text-rentara-blue">Ubah data kontrak</summary><form method="POST" action="{{ route('app.contracts.update', $contract) }}" class="mt-4 space-y-5">@csrf @method('PUT') @include('contracts._form', ['contract' => $contract, 'workspace' => $workspace])<button class="rounded-lg bg-rentara-blue px-4 py-2.5 text-sm font-semibold text-white">Simpan perubahan</button></form></details>@endif
        </section>

        <section class="rentara-card mt-6 p-6"><h2 class="font-display text-lg font-bold text-rentara-navy">Tenant kontrak</h2><p class="mt-1 text-sm text-slate-600">Pilih tenant yang berwenang Anda kelola. Data sensitif tenant tidak ditampilkan di sini.</p><div class="mt-4 space-y-2">@forelse($contract->tenants as $tenant)<div class="rounded-lg bg-slate-50 px-3 py-2 text-sm">{{ $tenant->name }} <span class="text-slate-500">· {{ $tenant->phone ?? 'Kontak tidak tersedia' }}</span></div>@empty<p class="text-sm text-slate-500">Belum ada tenant.</p>@endforelse</div>
            @if(in_array($status, ['draft','pending'], true))<form method="POST" action="{{ route('app.contracts.tenants.attach', $contract) }}" class="mt-4 flex flex-wrap items-end gap-3">@csrf<div class="min-w-64 flex-1"><label for="tenant_id" class="block text-sm font-semibold text-rentara-navy">Tambah tenant</label><select id="tenant_id" name="tenant_id" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih tenant</option>@foreach($availableTenants as $tenant)<option value="{{ $tenant->id }}">{{ $tenant->name }}</option>@endforeach</select>@error('tenant_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div><button class="rounded-lg bg-slate-700 px-4 py-2.5 text-sm font-semibold text-white">Tambahkan</button></form>@endif
        </section>

        <section class="rentara-card mt-6 p-6"><h2 class="font-display text-lg font-bold text-rentara-navy">Tindakan siklus hidup</h2><div class="mt-4 flex flex-wrap gap-3">
            @if($status === 'draft')<form method="POST" action="{{ route('app.contracts.submit',$contract) }}">@csrf<button class="rounded-lg bg-rentara-blue px-4 py-2.5 text-sm font-semibold text-white">Ajukan aktivasi</button></form>@endif
            @if($status === 'pending')<form method="POST" action="{{ route('app.contracts.activate',$contract) }}">@csrf<button class="rounded-lg bg-green-700 px-4 py-2.5 text-sm font-semibold text-white">Aktifkan</button></form>@endif
            @if(in_array($status, ['draft','pending','active'], true))<form method="POST" action="{{ route('app.contracts.cancel',$contract) }}" onsubmit="return confirm('Batalkan kontrak ini?');">@csrf<button class="rounded-lg border border-amber-300 px-4 py-2.5 text-sm font-semibold text-amber-800">Batalkan</button></form>@endif
            @if(in_array($status, ['active','expiring'], true))<form method="POST" action="{{ route('app.contracts.terminate',$contract) }}" class="flex flex-wrap items-end gap-2">@csrf<label for="termination-reason" class="sr-only">Alasan penghentian</label><input id="termination-reason" name="reason" required maxlength="1000" placeholder="Alasan penghentian" class="rounded-lg border-slate-300 text-sm"><button class="rounded-lg border border-red-300 px-4 py-2.5 text-sm font-semibold text-red-700" onclick="return confirm('Hentikan kontrak ini?')">Hentikan</button></form>@endif
        </div></section>

        @if(in_array($status, ['active','expiring'], true))<section class="rentara-card mt-6 p-6"><h2 class="font-display text-lg font-bold text-rentara-navy">Check-in / check-out</h2><div class="mt-4 grid gap-6 md:grid-cols-2"><form method="POST" action="{{ route('app.contracts.check-in',$contract) }}" class="space-y-3">@csrf<h3 class="font-semibold">Catat check-in</h3><div><label for="deposit_received" class="block text-sm font-semibold">Deposit diterima (Rp)</label><input id="deposit_received" name="deposit_received" type="number" min="0" inputmode="numeric" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div><div><label for="checkin-notes" class="block text-sm font-semibold">Catatan</label><textarea id="checkin-notes" name="notes" rows="2" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></textarea></div><button class="rounded-lg bg-rentara-blue px-4 py-2.5 text-sm font-semibold text-white">Simpan check-in</button></form><form method="POST" action="{{ route('app.contracts.check-out',$contract) }}" class="space-y-3">@csrf<h3 class="font-semibold">Catat check-out / settlement deposit</h3><div class="grid gap-3 sm:grid-cols-2"><div><label for="deposit_returned" class="block text-sm font-semibold">Deposit dikembalikan (Rp)</label><input id="deposit_returned" name="deposit_returned" type="number" min="0" inputmode="numeric" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div><div><label for="deposit_deduction" class="block text-sm font-semibold">Potongan deposit (Rp)</label><input id="deposit_deduction" name="deposit_deduction" type="number" min="0" inputmode="numeric" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div></div><div><label for="checkout-reason" class="block text-sm font-semibold">Alasan/catatan</label><textarea id="checkout-reason" name="reason" rows="2" maxlength="1000" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></textarea></div><button class="rounded-lg bg-slate-700 px-4 py-2.5 text-sm font-semibold text-white">Simpan check-out</button></form></div></section>@endif

        @if(in_array($status, ['active','expiring','completed','terminated'], true))<section class="rentara-card mt-6 p-6"><h2 class="font-display text-lg font-bold text-rentara-navy">Perpanjang kontrak</h2><form method="POST" action="{{ route('app.contracts.renew',$contract) }}" class="mt-4 space-y-5">@csrf@include('contracts._form', ['contract' => $contract, 'workspace' => $workspace])<button class="rounded-lg bg-rentara-blue px-4 py-2.5 text-sm font-semibold text-white">Buat kontrak perpanjangan</button></form></section>@endif
        <p class="mt-6 text-sm text-slate-500">Perhitungan tagihan/pembayaran dan dokumen kontrak belum diimplementasikan.</p>
    </div>
</x-app-layout>
