<script setup>
import { Head, useForm } from '@inertiajs/vue3';
const props = defineProps({ complaint: Object, is_organization: Boolean, organization_users: Array });
const comment = useForm({ body: '' });
const attachment = useForm({ attachment: null });
const update = useForm({ status: props.complaint.status, assigned_to: props.complaint.assigned_to?.id ?? '', resolution_notes: props.complaint.resolution_notes ?? '' });
function submitComment() { comment.post(`/complaints/${props.complaint.id}/comments`, { onSuccess: () => comment.reset() }); }
function submitAttachment() { attachment.post(`/complaints/${props.complaint.id}/attachments`, { forceFormData: true, onSuccess: () => attachment.reset() }); }
function updateComplaint() { update.patch(`/organizations/${props.complaint.organization_id}/complaints/${props.complaint.id}`); }
</script>
<template><Head :title="complaint.title" /><main class="mx-auto max-w-3xl space-y-6 p-6"><div><h1 class="text-2xl font-semibold">{{ complaint.title }}</h1><p class="mt-2 text-sm">{{ complaint.unit }} · {{ complaint.status }} · {{ complaint.priority }}</p></div><p class="whitespace-pre-wrap rounded-2xl border p-5">{{ complaint.description }}</p><form v-if="is_organization" @submit.prevent="updateComplaint" class="space-y-3 rounded-2xl border p-4"><select v-model="update.status" class="w-full rounded-xl border p-2"><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting_on_tenant">Waiting on tenant</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><select v-model="update.assigned_to" class="w-full rounded-xl border p-2"><option value="">Tidak ditugaskan</option><option v-for="user in organization_users" :value="user.id">{{ user.name }}</option></select><textarea v-model="update.resolution_notes" class="w-full rounded-xl border p-2" placeholder="Catatan penyelesaian"></textarea><button class="rounded-xl bg-[#47785a] px-4 py-2 text-white">Simpan</button></form><section><h2 class="mb-3 font-semibold">Timeline</h2><div v-for="item in complaint.comments" :key="item.id" class="mb-2 rounded-xl bg-gray-50 p-3"><b>{{ item.user }}</b><p>{{ item.body }}</p></div><form @submit.prevent="submitComment" class="mt-4 flex gap-2"><input v-model="comment.body" class="flex-1 rounded-xl border p-3" placeholder="Tulis komentar" /><button class="rounded-xl bg-[#47785a] px-4 text-white">Kirim</button></form><form v-if="!is_organization" @submit.prevent="submitAttachment" class="mt-3 flex gap-2"><input type="file" accept=".jpg,.jpeg,.png,.pdf" @change="attachment.attachment = $event.target.files[0]" /><button class="rounded-xl border px-4 py-2">Lampirkan</button></form></section></main></template>
