<?php
namespace App\Http\Controllers;
use App\Enums\{ContractStatus,TenantStatus,WorkspaceMemberRole};
use App\Models\{RentalContract,Property,Unit,Tenant,PropertyAssignment};
use App\Services\ContractLifecycleService;
use App\Support\AuditLogger;
use App\Support\OccupancyLockOrder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Illuminate\Database\QueryException;
class RentalContractController extends Controller {
 private function workspace(Request $r){return $r->attributes->get('currentWorkspace');}
 private function find(Request $r,int $id,bool $trashed=false):RentalContract{return RentalContract::where('workspace_id',$this->workspace($r)->id)->whereHas('property',fn($q)=>$q->where('workspace_id',$this->workspace($r)->id))->when($trashed,fn($q)=>$q->withTrashed())->findOrFail($id);}
 private function properties(Request $r){$w=$this->workspace($r);$role=$w->members()->where('user_id',$r->user()->id)->first()?->role;return Property::where('workspace_id',$w->id)->when($role!==WorkspaceMemberRole::Owner,fn($q)=>$q->whereIn('id',PropertyAssignment::where('workspace_id',$w->id)->where('user_id',$r->user()->id)->pluck('property_id')))->with('units')->orderBy('name')->get();}
  private function availableTenants(Request $r,RentalContract $c){$w=$this->workspace($r);$role=$w->members()->where('user_id',$r->user()->id)->first()?->role;$assigned=PropertyAssignment::where('workspace_id',$w->id)->where('user_id',$r->user()->id)->where('property_id',$c->property_id)->exists();return Tenant::where('workspace_id',$w->id)->where('status','active')->whereNull('deleted_at')->where(function($q)use($c,$role,$assigned){$q->where('unit_id',$c->unit_id);if($role===WorkspaceMemberRole::Owner||$role===WorkspaceMemberRole::Manager&&$assigned)$q->orWhereNull('unit_id');})->orderBy('name')->get();}
  private function rules():array{return ['property_id'=>['required','integer'],'unit_id'=>['required','integer'],'contract_number'=>['required','string','max:100'],'start_date'=>['required','date'],'end_date'=>['required','date','after_or_equal:start_date'],'rental_price'=>['required','integer','min:0'],'deposit_amount'=>['required','integer','min:0'],'notes'=>['nullable','string','max:2000']];}
  private function validateContractNumber(int $workspaceId,string $number,?int $exceptId=null):void
  {
   $query=RentalContract::withTrashed()->where('workspace_id',$workspaceId)->where('contract_number',$number);
   if($exceptId!==null)$query->where('id','!=',$exceptId);
   if($query->exists())throw ValidationException::withMessages(['contract_number'=>'Nomor kontrak sudah digunakan dalam workspace ini.']);
  }
  private function isContractNumberConstraint(QueryException $e):bool
  {
   $message=$e->getMessage();
   return in_array((string)$e->getCode(),['19','23000'],true)&&str_contains($message,'contract_number');
  }
  private function scoped(Request $r,array $d):array{$w=$this->workspace($r);$p=Property::where('workspace_id',$w->id)->findOrFail($d['property_id']);$u=Unit::where('workspace_id',$w->id)->where('property_id',$p->id)->findOrFail($d['unit_id']);$d['workspace_id']=$w->id;$d['property_id']=$p->id;$d['unit_id']=$u->id;return $d;}
  private function assertDestinationAssignment(Request $r,array $d):void{$w=$this->workspace($r);$member=$w->members()->where('user_id',$r->user()->id)->first();if($member?->role===WorkspaceMemberRole::Manager&&!PropertyAssignment::where('workspace_id',$w->id)->where('property_id',$d['property_id'])->where('user_id',$r->user()->id)->exists())abort(403);}
 public function index(Request $r){$w=$this->workspace($r);$this->authorize('viewAny',[RentalContract::class,$w]);$role=$w->members()->where('user_id',$r->user()->id)->first()?->role;$cs=RentalContract::where('workspace_id',$w->id)->when($role!==WorkspaceMemberRole::Owner,fn($q)=>$q->whereIn('property_id',PropertyAssignment::where('workspace_id',$w->id)->where('user_id',$r->user()->id)->pluck('property_id')))->with(['unit','tenants'])->latest()->paginate(15);return view('contracts.index',compact('w','cs'));}
 public function create(Request $r){$this->authorize('create',[RentalContract::class,$this->workspace($r)]);return view('contracts.create',['workspace'=>$this->workspace($r),'properties'=>$this->properties($r)]);}
  public function store(Request $r){$w=$this->workspace($r);$this->authorize('create',[RentalContract::class,$w]);$d=$r->validate($this->rules());$this->validateContractNumber($w->id,$d['contract_number']);$d=$this->scoped($r,$d);$member=$w->members()->where('user_id',$r->user()->id)->first();abort_if($member?->role===WorkspaceMemberRole::Manager&&!PropertyAssignment::where('property_id',$d['property_id'])->where('user_id',$r->user()->id)->exists(),403);try{$c=RentalContract::create($d);}catch(QueryException $e){if($this->isContractNumberConstraint($e))throw ValidationException::withMessages(['contract_number'=>'Nomor kontrak sudah digunakan dalam workspace ini.']);throw $e;}return redirect()->route('app.contracts.show',$c)->with('status','Kontrak berhasil dibuat.');}
 public function show(Request $r,int $contract){$c=$this->find($r,$contract)->load(['unit','property','tenants','checkIn','checkOut']);$this->authorize('view',$c);return view('contracts.show',['workspace'=>$this->workspace($r),'contract'=>$c,'properties'=>$this->properties($r),'availableTenants'=>$this->availableTenants($r,$c)]);}
    public function update(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('update',$c);$d=$r->validate($this->rules());$c=DB::transaction(function()use($r,$c,$d){$scoped=$this->scoped($r,$d);$this->assertDestinationAssignment($r,$scoped);$units=OccupancyLockOrder::units([$c->unit_id,$scoped['unit_id']],$c->workspace_id);$locked=OccupancyLockOrder::contracts([$c->id],$c->workspace_id)->get($c->id);if(!$locked||!in_array($locked->status,[ContractStatus::Draft,ContractStatus::Pending,ContractStatus::Cancelled],true))throw ValidationException::withMessages(['status'=>'Kontrak aktif tidak dapat diubah langsung.']);$this->validateContractNumber($locked->workspace_id,$scoped['contract_number'],$locked->id);$destination=$units->get($scoped['unit_id']);$tenantIds=$locked->tenants()->where('tenants.status',TenantStatus::Active->value)->whereNull('tenants.deleted_at')->pluck('tenants.id')->sort()->values();OccupancyLockOrder::tenants($tenantIds,$locked->workspace_id);if($tenantIds->count()>$destination->capacity)throw ValidationException::withMessages(['tenant_id'=>'Jumlah tenant melebihi kapasitas unit.']);try{$locked->update($scoped);}catch(QueryException $e){if($this->isContractNumberConstraint($e))throw ValidationException::withMessages(['contract_number'=>'Nomor kontrak sudah digunakan dalam workspace ini.']);throw $e;}return $locked;});return redirect()->route('app.contracts.show',$c)->with('status','Perubahan kontrak berhasil disimpan.');}
   public function destroy(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('delete',$c);if(!in_array($c->status,[ContractStatus::Draft,ContractStatus::Cancelled],true))abort(422,'Hanya kontrak draft atau dibatalkan yang dapat dihapus.');DB::transaction(function()use($c){$unit=OccupancyLockOrder::units([$c->unit_id],$c->workspace_id);$locked=OccupancyLockOrder::contracts([$c->id],$c->workspace_id)->get($c->id);if(!$locked||!in_array($locked->status,[ContractStatus::Draft,ContractStatus::Cancelled],true))abort(422,'Hanya kontrak draft atau dibatalkan yang dapat dihapus.');$locked->delete();app(AuditLogger::class)->contractDeleted(auth()->user(),$locked);});return redirect()->route('app.contracts.index')->with('status','Kontrak berhasil dihapus.');}
  public function restore(Request $r,int $contract){$c=$this->find($r,$contract,true);$this->authorize('restore',$c);if($c->trashed())app(ContractLifecycleService::class)->restore($c);return redirect()->route('app.contracts.show',$c)->with('status','Kontrak berhasil dipulihkan.');}
 public function submit(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('update',$c);app(ContractLifecycleService::class)->submit($c);return back()->with('status','Kontrak diajukan untuk aktivasi.');}
 public function activate(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('update',$c);app(ContractLifecycleService::class)->activate($c);return back()->with('status','Kontrak berhasil diaktifkan.');}
 public function cancel(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('update',$c);app(ContractLifecycleService::class)->cancel($c);return back()->with('status','Kontrak dibatalkan.');}
  public function terminate(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('update',$c);$d=$r->validate(['reason'=>['required','string','max:1000','regex:/.*\S.*/']]);app(ContractLifecycleService::class)->terminate($c,$d['reason']);return back()->with('status','Kontrak dihentikan.');}
   public function renew(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('update',$c);$d=$r->validate(['contract_number'=>'required|string|max:100','start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date','rental_price'=>'required|integer|min:0','deposit_amount'=>'required|integer|min:0']);$this->validateContractNumber($c->workspace_id,$d['contract_number']);try{$new=app(ContractLifecycleService::class)->renew($c,$d);}catch(QueryException $e){if($this->isContractNumberConstraint($e))throw ValidationException::withMessages(['contract_number'=>'Nomor kontrak sudah digunakan dalam workspace ini.']);throw $e;}return redirect()->route('app.contracts.show',$new)->with('status','Kontrak perpanjangan berhasil dibuat.');}
   public function attachTenant(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('update',$c);$d=$r->validate(['tenant_id'=>'required|integer']);DB::transaction(function()use($r,$c,$d){$unit=OccupancyLockOrder::units([$c->unit_id],$c->workspace_id)->get($c->unit_id);$locked=OccupancyLockOrder::contracts([$c->id],$c->workspace_id)->get($c->id);$t=OccupancyLockOrder::tenants([$d['tenant_id']],$c->workspace_id)->get($d['tenant_id']);if(!$unit||!$locked||!$t)abort(404);$role=$this->workspace($r)->members()->where('user_id',$r->user()->id)->first()?->role;$assigned=PropertyAssignment::where('workspace_id',$locked->workspace_id)->where('user_id',$r->user()->id)->where('property_id',$locked->property_id)->exists();if($role!==WorkspaceMemberRole::Owner&&!$assigned)throw ValidationException::withMessages(['tenant_id'=>'Tenant tidak terlihat pada properti yang ditugaskan.']);if(!in_array($locked->status,[ContractStatus::Draft,ContractStatus::Pending],true))throw ValidationException::withMessages(['status'=>'Tenant hanya dapat diubah pada kontrak draft atau menunggu.']);if($t->unit_id!==null&&(int)$t->unit_id!==(int)$locked->unit_id)throw ValidationException::withMessages(['tenant_id'=>'Tenant sudah ditugaskan ke unit lain.']);if($locked->tenants()->whereKey($t->id)->exists())return;$count=$locked->tenants()->where('tenants.status','active')->whereNull('deleted_at')->count();if($t->status->value==='active'&&$count >= $unit->capacity)throw ValidationException::withMessages(['tenant_id'=>'Kapasitas unit sudah penuh.']);$locked->tenants()->attach($t->id,['workspace_id'=>$locked->workspace_id]);app(AuditLogger::class)->contractTenantAttached(auth()->user(),$locked,$t->id);});return back()->with('status','Tenant kontrak berhasil ditambahkan.');}
 public function checkIn(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('operate',$c);$d=$r->validate(['checked_in_at'=>'nullable|date','deposit_received'=>'nullable|integer|min:0','notes'=>'nullable|string|max:2000']);app(ContractLifecycleService::class)->checkIn($c,$d);return back()->with('status','Check-in berhasil dicatat.');}
  public function checkOut(Request $r,int $contract){$c=$this->find($r,$contract);$this->authorize('operate',$c);$d=$r->validate(['checked_out_at'=>'nullable|date','unpaid_amount'=>'nullable|integer|min:0','damage_amount'=>'nullable|integer|min:0','deposit_returned'=>'nullable|integer|min:0','deposit_deduction'=>'nullable|integer|min:0','reason'=>'nullable|string|max:1000','notes'=>'nullable|string|max:2000']);if(!$c->checkIn()->exists()&&(int)($d['deposit_returned']??0)+(int)($d['deposit_deduction']??0)>(int)$c->deposit_amount)throw ValidationException::withMessages(['deposit_returned'=>'Penyelesaian deposit melebihi nilai deposit.']);app(ContractLifecycleService::class)->checkOut($c,$d);return back()->with('status','Check-out berhasil dicatat.');}
}
