<x-app-layout>
    <div class="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8">
        <p class="text-sm font-semibold text-rentara-teal">Ruang kerja aktif: {{ $w->name }}</p><h1 class="rentara-page-title mt-2">Buat invoice</h1><p class="mt-2 text-slate-600">Masukkan data tagihan manual. Status dan mata uang ditentukan oleh server.</p>
        @if($contracts->isEmpty())<div class="rentara-card mt-6" role="status"><h2 class="font-display text-lg font-bold text-rentara-navy">Belum ada kontrak yang tersedia</h2><p class="mt-2 text-sm text-slate-600">Invoice membutuhkan kontrak aktif dengan tenant yang bertanggung jawab.</p></div>@else
        <form method="post" action="{{ route('app.invoices.store') }}" class="rentara-card mt-6 space-y-5">@csrf
            <div><label for="contract_id" class="block text-sm font-semibold text-rentara-navy">Kontrak</label><select id="contract_id" name="contract_id" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih kontrak</option>@foreach($contracts as $contract)<option value="{{ $contract->id }}" @selected((string)old('contract_id') === (string)$contract->id)>{{ $contract->contract_number }} · {{ $contract->property?->name }} · {{ $contract->unit?->unit_number ?? '—' }}</option>@endforeach</select>@error('contract_id')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div>
            <div><label for="tenant_id" class="block text-sm font-semibold text-rentara-navy">Tenant yang bertanggung jawab</label><select id="tenant_id" name="tenant_id" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih tenant</option>@foreach($contracts->flatMap->tenants->unique('id') as $tenant)<option value="{{ $tenant->id }}" @selected((string)old('tenant_id') === (string)$tenant->id)>{{ $tenant->name }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Hanya tenant yang terhubung ke kontrak terpilih yang dapat disimpan.</p>@error('tenant_id')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label for="invoice_number" class="block text-sm font-semibold text-rentara-navy">Nomor invoice</label><input id="invoice_number" name="invoice_number" value="{{ old('invoice_number') }}" required maxlength="100" class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('invoice_number')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div><div><label for="amount" class="block text-sm font-semibold text-rentara-navy">Jumlah tagihan</label><input id="amount" name="amount" type="number" min="1" inputmode="numeric" value="{{ old('amount') }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('amount')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div></div>
            <div class="grid gap-5 sm:grid-cols-3"><div><label for="period_start" class="block text-sm font-semibold text-rentara-navy">Periode mulai</label><input id="period_start" name="period_start" type="date" value="{{ old('period_start') }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('period_start')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div><div><label for="period_end" class="block text-sm font-semibold text-rentara-navy">Periode selesai</label><input id="period_end" name="period_end" type="date" value="{{ old('period_end') }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('period_end')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div><div><label for="due_date" class="block text-sm font-semibold text-rentara-navy">Jatuh tempo</label><input id="due_date" name="due_date" type="date" value="{{ old('due_date') }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('due_date')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div></div>
            <div class="flex flex-wrap gap-3"><button type="submit" class="rounded-lg bg-rentara-blue px-4 py-2.5 text-sm font-semibold text-white hover:opacity-90">Simpan invoice</button><a href="{{ route('app.invoices.index') }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Batal</a></div>
        </form>@endif
    </div>
</x-app-layout>
