<x-app-layout>
    <div class="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8"><p class="text-sm font-semibold text-rentara-teal">Ruang kerja aktif: {{ $w->name }}</p><h1 class="rentara-page-title mt-2">Ubah invoice</h1><p class="mt-2 text-slate-600">Hanya invoice yang belum dibayar yang dapat diubah.</p>
        <form method="post" action="{{ route('app.invoices.update', $invoice) }}" class="rentara-card mt-6 space-y-5">@csrf @method('PUT')
            <div><label for="invoice_number" class="block text-sm font-semibold text-rentara-navy">Nomor invoice</label><input id="invoice_number" name="invoice_number" value="{{ old('invoice_number', $invoice->invoice_number) }}" required maxlength="100" class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('invoice_number')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label for="amount" class="block text-sm font-semibold text-rentara-navy">Jumlah tagihan</label><input id="amount" name="amount" type="number" min="1" inputmode="numeric" value="{{ old('amount', $invoice->amount) }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('amount')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div><div><p class="text-sm font-semibold text-rentara-navy">Mata uang</p><p class="mt-2 text-sm text-slate-600">{{ $invoice->currency }} (ditentukan server)</p></div></div>
            <div class="grid gap-5 sm:grid-cols-3"><div><label for="period_start" class="block text-sm font-semibold text-rentara-navy">Periode mulai</label><input id="period_start" name="period_start" type="date" value="{{ old('period_start', $invoice->period_start->format('Y-m-d')) }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('period_start')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div><div><label for="period_end" class="block text-sm font-semibold text-rentara-navy">Periode selesai</label><input id="period_end" name="period_end" type="date" value="{{ old('period_end', $invoice->period_end->format('Y-m-d')) }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('period_end')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div><div><label for="due_date" class="block text-sm font-semibold text-rentara-navy">Jatuh tempo</label><input id="due_date" name="due_date" type="date" value="{{ old('due_date', $invoice->due_date->format('Y-m-d')) }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('due_date')<p class="mt-1 text-sm text-red-700" role="alert">{{ $message }}</p>@enderror</div></div>
            <div class="flex flex-wrap gap-3"><button type="submit" class="rounded-lg bg-rentara-blue px-4 py-2.5 text-sm font-semibold text-white hover:opacity-90">Simpan perubahan</button><a href="{{ route('app.invoices.show', $invoice) }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Batal</a></div>
        </form>
    </div>
</x-app-layout>
