<x-app-layout>
    <div class="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
        @php($status = $invoice->is_overdue ? 'Terlambat' : ($invoice->status->value === 'paid' ? 'Lunas' : 'Belum dibayar'))
        <p class="text-sm font-semibold text-rentara-teal">Ruang kerja aktif: {{ $w->name }}</p>
        <div class="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 class="rentara-page-title">{{ $invoice->invoice_number }}</h1><p class="mt-2 text-slate-600">Detail invoice manual</p></div><span role="status">{{ $status }}</span></div>
        @if(session('status'))<p class="mt-4 rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm font-medium text-green-800" role="status">{{ session('status') }}</p>@endif
        @if($errors->has('invoice'))<div class="mt-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">{{ $errors->first('invoice') }}</div>@endif
        <section class="rentara-card mt-6"><h2 class="font-display text-lg font-bold text-rentara-navy">Ringkasan tagihan</h2><dl class="mt-4 grid gap-5 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Jumlah</dt><dd>{{ $invoice->currency }} {{ number_format($invoice->amount, 0, ',', '.') }}</dd></div><div><dt class="text-sm text-slate-500">Periode</dt><dd>{{ $invoice->period_start->format('d/m/Y') }} – {{ $invoice->period_end->format('d/m/Y') }}</dd></div><div><dt class="text-sm text-slate-500">Jatuh tempo</dt><dd>{{ $invoice->due_date->format('d/m/Y') }}</dd></div><div><dt class="text-sm text-slate-500">Tenant bertanggung jawab</dt><dd>{{ $invoice->tenant?->name ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">Unit / properti</dt><dd>{{ $invoice->contract?->unit?->unit_number ?? '—' }} · {{ $invoice->property?->name ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">Kontrak</dt><dd>{{ $invoice->contract?->contract_number ?? '—' }}</dd></div></dl></section>
        @if($invoice->status->value === 'paid')
            @php($paymentMethod = ['cash' => 'Tunai', 'bank_transfer' => 'Transfer bank', 'other' => 'Lainnya'][$invoice->payment_method] ?? '—')
<section class="rentara-card mt-6"><h2 class="font-display text-lg font-bold text-rentara-navy">Pembayaran tercatat</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Tanggal pembayaran</dt><dd>{{ $invoice->paid_date?->format('d/m/Y') ?? '—' }}</dd></div><div><dt class="text-sm text-slate-500">Metode</dt><dd>{{ $paymentMethod }}</dd></div></dl></section>
        @else
            <div class="mt-6 flex flex-wrap gap-3">@can('update', $invoice)<a href="{{ route('app.invoices.edit', $invoice) }}" class="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Ubah invoice</a>@endcan</div>
            @can('pay', $invoice)<section class="rentara-card mt-6"><h2 class="font-display text-lg font-bold text-rentara-navy">Catat pelunasan</h2><form method="post" action="{{ route('app.invoices.pay', $invoice) }}" class="mt-5 space-y-4">@csrf<div class="grid gap-4 sm:grid-cols-2"><div><label for="payment_date">Tanggal pembayaran</label><input id="payment_date" type="date" name="payment_date" value="{{ old('payment_date', now()->toDateString()) }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm">@error('payment_date')<p role="alert">{{ $message }}</p>@enderror</div><div><label for="payment_method">Metode pembayaran</label><select id="payment_method" name="payment_method" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Pilih metode</option><option value="cash" @selected(old('payment_method') === 'cash')>Tunai</option><option value="bank_transfer" @selected(old('payment_method') === 'bank_transfer')>Transfer bank</option><option value="other" @selected(old('payment_method') === 'other')>Lainnya</option></select>@error('payment_method')<p role="alert">{{ $message }}</p>@enderror</div></div><div><label for="payment_reference">Referensi (opsional)</label><input id="payment_reference" name="payment_reference" maxlength="255" value="{{ old('payment_reference') }}" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div><div><label for="payment_notes">Catatan (opsional)</label><textarea id="payment_notes" name="payment_notes" maxlength="2000" class="mt-1 block w-full rounded-lg border-slate-300 text-sm">{{ old('payment_notes') }}</textarea></div><button type="submit" class="rounded-lg bg-rentara-blue px-4 py-2.5 text-sm font-semibold text-white">Catat pembayaran</button></form></section>@endcan
        @endif
    </div>
</x-app-layout>
